ts baby (#28)
- **build(deps): bump zod from 4.2.1 to 4.3.5**
- **typo**
- **fix: typescript is the way**

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Doug Chimento <doug@corsa.finance>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,25 +1,25 @@
 name: ci-config
 description: config ci config
 author: Cartera Mesh
-
 branding:
   icon: scissors
   color: black
-
-# Define your inputs here.
-inputs:
-  config:
-    description: file path or JSON string
-    required: true
-  runner:
-    description: github runner name
-    required: false
-
-# Define your outputs here.
 outputs:
   config:
     description: JSON string of the config
-
+    value: ${{ steps.generate.outputs.config }}
 runs:
-  using: node24
-  main: dist/index.js
+  using: composite
+  steps:
+    - name: setup bun
+      uses: oven-sh/setup-bun@v2
+    - id: generate
+      name: generate
+      shell: bash
+      run: |
+        if [ ! -f .github/rust-ci.ts ]; then
+          echo "::error::Missing .github/rust-ci.ts config file"
+          exit 1
+        fi
+        CONFIG="$(bun run ${{ github.action_path }}/scripts/generate-rust.ts | jq . --compact-output )"
+        echo "config=$CONFIG" >> $GITHUB_OUTPUT
